### ISSUE TITLE
home.html

### ISSUE THREAD

**Issue by rogersmykenzie** [KeenanRileyFaulkner/devmtn-assessment-3#1]
Remember with `ul` tags we probably want to nest our text content within `li` tags inside those `ul`s. If we don't want the bullets or any of the standard styling we can remove or change the appearance with css.

https://github.com/KeenanRileyFaulkner/devmtn-assessment-3/blob/9cdd8c0ff5abc2d9d5f20bbfaa70b7bae67a4f90/home.html#L25-L27

Nice job!

**Comment by KeenanRileyFaulkner** [comment]
Refactored. Thanks for catching that.
